name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/lexmargin/kube-operator:latest
      - name: Push image to AliCloud
        run: |
          docker version
          # login to aliCloud image repository
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # push image to aliCloud private repository
          docker push registry.cn-hangzhou.aliyuncs.com/lexmargin/kube-operator:latest